apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osv-offline-db              
  namespace: mintmaker        
spec:
  accessModes:
    - ReadWriteOnce           
  resources:
    requests:
      storage: 1Gi            
  volumeMode: Filesystem
