apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osv-offline-db2             
  namespace: mintmaker        
spec:
  accessModes:
    - ReadWriteOnce           
  resources:
    requests:
      storage: 10Gi            
  volumeMode: Filesystem
