apiVersion: v1
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: quay-registry
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    DISTRIBUTED_STORAGE_CONFIG:
      default:
        - RadosGWStorage
        - access_key: minio
          secret_key: minio123
          bucket_name: quay
          hostname: minio.quay-registry.svc.cluster.local
          port: 9000
          is_secure: false
          storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
      - default
    DISTRIBUTED_STORAGE_PREFERENCE:
      - default
